// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsatzhubndgogeaavldy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYXR6aHVibmRnb2dlYWF2bGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTEyNDksImV4cCI6MjA3MjY4NzI0OX0.YXu8Y-e5ru5qBVIu8nbOGTV0IEtVcbgsKB3yrYIa9BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});